export const USER_TOKEN = 'USER_TOKEN'
export const DATA_ENTRIES = 'DATA_ENTRIES'
export const ONBOARDING_STEP = 'ONBOARDING_STEP'
export const SURVEY_TOKEN = 'SURVEY_TOKEN'
export const SURVEY_ID = 'SURVEY_ID'
export const SURVEY_TABLE_KEY = 'SURVEY_TABLE_KEY'
export const DAILY_DATA_ENTRIES = 'DAILY_DATA_ENTRIES'

export const ONBOARDING_STEPS = {
  WELCOME: 'WELCOME',
  SETUP: 'SETUP',
  DASHBOARD: 'DASHBOARD',
  CONFIRM_ACCESS_CODE: 'CONFIRM_ACCESS_CODE',
}
